from django.db.models.enums import TextChoices


class InstituicaoChoices(TextChoices):
    NAOINFORMADO = "", "Selecione..."
    CAMPUS_ARACAJU = 8474494, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE - CAMPUS ARACAJU"
    CAMPUS_ESTANCIA = 8474496, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE - CAMPUS ESTÂNCIA"
    CAMPUS_ITABAIANA = 8474498, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE - CAMPUS ITABAIANA"
    CAMPUS_LAGARTO = 8474499, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE - CAMPUS LAGARTO"
    CAMPUS_NOSSA_SENHORA_GLORIA = 8474501, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE - CAMPUS NOSSA SENHORA DA GLÓRIA"
    CAMPUS_SAO_CRISTOVAO = 8474504, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE - CAMPUS SÃO CRISTÓVÃO"
    CAMPUS_NOSSA_SENHORA_SOCORRO = 8474507, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE CAMPUS NOSSA SENHORA DO SOCORRO"
    CAMPUS_POCO_REDONDO = 8474510, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE CAMPUS POÇO REDONDO"
    CAMPUS_PROPRIA = 8474514, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE CAMPUS PROPRIÁ"
    CAMPUS_TOBIAS_BARRETO = 8474516, "GESTOR DA UNIDADE DE ENSINO - INSTITUTO FEDERAL DE SERGIPE CAMPUS TOBIAS BARRETO"
