# Generated by Django 3.2.14 on 2025-02-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistec.instituicao'),
            preserve_default=False,
        ),
    ]
